apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhkmer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhkmer
  template:
    metadata:
      labels:
        app: dhkmer
    spec:
      containers:
      - image: okteto.dev/dhkmer:latest
        name: dhkmer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d3564517-b85a-46b8-aff8-f7d514ab2d4a"
        - name: Vless_Path
          value: "/vl7u777b55"
        - name: Vmess_UUID
          value: "d3564517-b85a-46b8-aff8-f7d514ab2d4a"
        - name: Vmess_Path
          value: "/vm66vbb456"
        - name: Share_Path
          value: "/v2link"
